- name: Create Docker keyrings dir
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Set Docker architecture
  ansible.builtin.set_fact:
    docker_arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/debian
      {{ ansible_facts.distribution_release }} stable
    filename: docker
    state: present

- name: Install Docker and Compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Enable Docker
  systemd:
    name: docker
    enabled: true
    state: started

- name: Add user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: true